theme:
  name: material
  favicon: images/favicon.ico
  logo: images/EIDF_rgb.png
  palette:
    scheme: default
  features:
    - tabs
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/eidf.css
  - stylesheets/access.css

site_name: EIDF User Documentation
site_url: https://epcced.github.io/eidf-docs/
repo_url: https://github.com/EPCCed/eidf-docs/
repo_name: EPCCed/eidf-docs.git
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list


nav:
  - "Service Status": status/index.md
  - "Documentation overview": index.md
  - "About EIDF":
    - "Introduction": overview/index.md
    - "Acknowledgements": overview/acknowledgements.md
    - "Contact": overview/contacts.md
  - "Service Access":
    - "Web vs SSH": access/index.md
    - "EIDF Web Portal": access/project.md
    - "Virtual Desktop Interface": access/virtualmachines-vdi.md
  - "Computing Services":
    - "Data Science Virtual Desktops":
      - "QuickStart": services/virtualmachines/quickstart.md
      - "Managing VMs": services/virtualmachines/docs.md
      - "Virtual Desktop Interface": access/virtualmachines-vdi.md
      - "SSH Access to VMs": access/ssh.md
    - "Managed JupyterHub":
      - "QuickStart": services/jhub/quickstart.md
      - "Tutorial": services/jhub/tutorial.md
      - "Documentation": services/jhub/docs.md
    - "Cerebras CS-1":
      - "Get Access": services/cs1/access.md
      - "Running codes": services/cs1/run.md
    - "Ultra2":
      - "Get Access": services/ultra2/access.md
      - "Running codes": services/ultra2/run.md
  - "Data Management Services":
    - "Data Catalogue":
      - "QuickStart": services/datacatalogue/quickstart.md
      - "Tutorial": services/datacatalogue/tutorial.md
      - "Documentation": services/datacatalogue/docs.md
      - "Metadata information": services/datacatalogue/metadata.md
  - "Bespoke Services":
    - "Ed-DaSH Workshops: Notebook Service": access/workshops/workshops.md
    - "Ed-DaSH Workshops: Virtual Machines": access/workshops/safe-registration.md
    - "JupyterHub Notebook Service Access": access/workshops/jhub-git.md
  - "EIDF Known Issues": known-issues/index.md
  - "EIDF Frequently Asked Questions": faq/index.md
