theme:
  name: material
  favicon: images/favicon.ico
  logo: images/EIDF_rgb.png
  palette:
    scheme: default
  features:
    - tabs
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/eidf.css

site_name: EIDF User Documentation
site_url: https://epcced.github.io/eidf-docs/
repo_url: https://github.com/EPCCed/eidf-docs.git
repo_name: EPCCed/eidf-docs.git
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - "Documentation overview": index.md
  - "EIDF: Introduction": overview/index.md
  - "Metadata information": metadata.md
  - "EIDF Known Issues": known-issues/index.md
  - "EIDF Frequently Asked Questions": faq/index.md
