theme:
  name: material
  palette:
    scheme: default
  features:
    - tabs
  icon:
    repo: fontawesome/brands/github


site_name: EIDF User Documentation
repo_url: https://github.com/EPCCed/eidf-docs.git
repo_name: EPCCed/eidf-docs.git
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - "Documentation overview": index.md
  - "Metadata information": metadata.md
