blank_issues_enabled: false
contact_links:
  - name: EIDF
    url: https://www.ed.ac.uk/edinburgh-international-data-facility
    about: For information about EIDF Services and more contact details.
  - name: EPCC
    url: http://www.epcc.ed.ac.uk/contact
    about: For information about EPCC Services and more contact details.
